### ISSUE TITLE
Member Card Layout Wrong on Mobile

### ISSUE THREAD

**Issue by ClydeFrog04** [Laarzae-Studios/PMR#22]
On some mobile devices, iPhoneX and galaxy s5 for example, the member cards are offset to the right, this does not occur on all mobile devices however. The pixel 2 seems to be unaffected.
![image](https://user-images.githubusercontent.com/31398520/119915539-f62d7e00-bf1f-11eb-8cfb-835e4b3bdd16.png)

**Comment by tdubs42** [comment]
Issue is fixed. Waiting for merge approval. GH #24

**Comment by ClydeFrog04** [comment]
Just reopening so we can close it with a pr so they are connected.
